services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crewboard
      POSTGRES_PASSWORD: "Zl_ZF_59HLDcQsdjo1S-aAgeLyYjaTGU"
    volumes:
      - crewboard_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "xKz3MhQyUOt1RDgBtzs2ZEadIwoPM-_W"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crewboard_test
      POSTGRES_PASSWORD: "npTX9zmUCokyeZsEtUC4HRekP7WvLA28"
    volumes:
      - crewboard_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "mdnGB2aO__opRd3YOWoPkZ1_DEOdFzT4"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  crewboard_data:
  crewboard_test_data:
